spring:
  profiles:
    include: API-KEY

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  config:
    import: classpath:/character.yml, classpath:/mysqlDB.yml

logging.level:
  org.hibernate.SQL: false

server:
  session:
    tracking-modes: cookie

  error:
    whitelabel:
      enabled=false:
# org.hibernate.type: trace
# 파라미터 바인딩 된 것 까지 볼 수 있음

