spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    import: classpath:/dnfData.yml

logging.level:
  org.hibernate.SQL: false

server:
  session:
    tracking-modes: cookie

  port: 80

image: ${IMAGE_PATH}
dnf-api-key: ${DNF_API_KEY}
# org.hibernate.type: trace
# 파라미터 바인딩 된 것 까지 볼 수 있음

